FROM python:3.9


RUN adduser lizard
USER lizard
WORKDIR /home/lizard
ENV PATH="/home/lizard/.local/bin:${PATH}"

RUN pip3 install lizard --disable-pip-version-check

COPY lizard.sh .


WORKDIR /tmp/lizard
CMD bash /home/lizard/lizard.sh

